name: Node CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0

      - name: Install dependencies
        run: pnpm ci

      - name: Run linter
        run: pnpm run lint

      - name: Run tests
        run: pnpm run coverage
